name: banana_query_drift
description: Drift-based database implementation for BananaQuery SDK
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.4.1

dependencies:
  drift: ^2.14.1
  sqlite3: ^2.4.0
  path: ^1.8.3
  banana_query_core: 
    git:
      url: https://github.com/BananaQuery/bananaquery_dart_sdk/
      path: packages/banana_query_core
      ref: main
  banana_query_database:
    git:
      url: https://github.com/BananaQuery/bananaquery_dart_sdk/
      path: packages/banana_query_database
      ref: main

dev_dependencies:
  drift_dev: ^2.14.1
  build_runner: ^2.4.7
  lints: ^3.0.0
  test: ^1.24.0
