name: banana_query_couchbase
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.1

# Add regular dependencies here.
dependencies:
  uuid: ^3.0.6
  cbl_flutter: ^3.3.5
  banana_query_core: 
    git:
      url: https://github.com/BananaQuery/bananaquery_dart_sdk/
      path: packages/banana_query_core
      ref: main
  banana_query_database:
    git:
      url: https://github.com/BananaQuery/bananaquery_dart_sdk/
      path: packages/banana_query_database
      ref: main
  # path: ^1.8.0

dev_dependencies:
  cbl_dart: ^3.0.1
  lints: ^3.0.0
  test: ^1.24.0
